layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  exclude:
    archived: false
    forks: true
    projects:
     - hello
     - resources
     - portfolio
     - official-website
     - hightechu-spring2019
     - hightechu-academy-project-fantasticblackberry
     - wp-bootstrap-navwalker
     - flarum-ext-ajax
     - awesome-quantum-software

social_media:
  facebook: hightechu
  instagram: hightechu
  linkedin: hightechu
  twitter: hightech_u
  website: https://www.hightechu.ca
  youtube: channel/UC2Mn8IgijRO-OF-DrWEq4KA?
