layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  exclude:
    archived: false
    forks: true
    projects:
     - hello
     - resources
     - portfolio
     - official-website
     - hightechu-spring2019
     - hightechu-academy-project-fantasticblackberry
     - wp-bootstrap-navwalker
     - flarum-ext-ajax
     - awesome-quantum-software
     - flarum-ext-aqueduct
     - hightechq
     - hightechu-summer2020
     - sci-fi-or-fantasy-data
     - hub-project-scifi-or-fantasy
     - hub-project-say-what-you-see
     - links
     - internship-application-CSJ-2020
     - jasonette

social_media:
  facebook: hightechu
  instagram: hightechu_ca
  linkedin: hightechu
  twitter: hightech_cu
  website: https://www.hightechu.ca
  youtube: channel/UC2Mn8IgijRO-OF-DrWEq4KA?
